name: Sync Fork

on:
  schedule:
    - cron: '0 */12 */3 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: sync
        run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}

      - name: checkout_actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: rebase
        run: |
          cd $GITHUB_WORKSPACE
          git remote add upstream $UPSTREAM_URL
          git fetch upstream $BRANCH_NAME
          git rebase upstream/$BRANCH_NAME
          git push -f origin $BRANCH_NAME
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          UPSTREAM_URL: "https://github.com/sophgo/fsbl.git"
